on:
  push:
    branches: dev

name: 🚀 Deploy dev-site on push on the dev branch
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: 🔨 pkg installation and build
        run: |
          npm install
          npm run build

      - name: 📂 Sync  file to server 1
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_pwd }}
          exclude: |
            **/.vscode/**
            **/.git*
            **/.git*/**
            **/node_modules/**
          server-dir: ./techbysj.mwerothewebmaker.com/
          dangerous-clean-slate: true

      - name: 📂 Deploy to server 2
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_pwd }}
          exclude: |
            **/.vscode/**
            **/.git*
            **/.git*/**
            **/node_modules/**

          server-dir: ./pokemons.mwerothwebmaker.com/
          # dangerous-clean-slate : true
